export const BEIGE = "beige"
export const PINK = "pink"
export const BACKGROUND = "background"
export const BACKGROUND_FRONT = "background-front"
export const TEXT = "text"
export const TEXT_STRONG = "text-strong"
export const BLACK = "black"
export const WHITE = "white"
